rvm:
  - 1.9.3
  - 2.0.0
before_install:
  - sudo mkdir -p /opt/ruby/bin && sudo ln -s `which ruby` /opt/ruby/bin/ruby
  - sudo mkdir -p /opt/ruby/bin && sudo ln -s `which bundle` /opt/ruby/bin/bundle

